### ISSUE TITLE
你tm劈我瓜是吧？

### ISSUE THREAD

**Issue by ArmedImmediatel** [sevente17/sevente17.github.io#2]

**Comment by ArmedImmediatel** [comment]
直接来吧

**Comment by ArmedImmediatel** [comment]
啊啊啊啊啊啊啊啊啊

**Comment by ArmedImmediatel** [comment]
你要不要吧

**Comment by sevente17** [comment]
不要（滑稽
________________________________
发件人: ArmedImmediatel ***@***.***>
发送时间: 2022年5月1日 10:52
收件人: sevente17/sevente17.github.io ***@***.***>
抄送: Subscribed ***@***.***>
主题: Re: [sevente17/sevente17.github.io] 你tm劈我瓜是吧？ (Issue #2)


你要不要吧

―
